### ISSUE TITLE
`KeyError` in canonicalize_modifications

### ISSUE THREAD

**Issue by jbarnoud** [marrink-lab/vermouth-martinize#354] opened 2021-03-15 12:06 UTC
```
Traceback (most recent call last):
  File "/home/jon/miniconda3/envs/vermouth/bin/martinize2", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/mnt/c/Users/dr19502/PDB/src/vermouth-martinize/bin/martinize2", line 808, in <module>
    entry()
  File "/mnt/c/Users/dr19502/PDB/src/vermouth-martinize/bin/martinize2", line 621, in entry
    system = pdb_to_universal(
  File "/mnt/c/Users/dr19502/PDB/src/vermouth-martinize/bin/martinize2", line 134, in pdb_to_universal
    vermouth.CanonicalizeModifications().run_system(canonicalized)
  File "/mnt/c/Users/dr19502/PDB/src/vermouth-martinize/vermouth/processors/processor.py", line 37, in run_system
    mols.append(self.run_molecule(molecule))
  File "/mnt/c/Users/dr19502/PDB/src/vermouth-martinize/vermouth/processors/canonicalize_modifications.py", line 370, in run_molecule
    fix_ptm(molecule)
  File "/mnt/c/Users/dr19502/PDB/src/vermouth-martinize/vermouth/processors/canonicalize_modifications.py", line 302, in fix_ptm
    residue = molecule.subgraph(n_idxs)
  File "/mnt/c/Users/dr19502/PDB/src/vermouth-martinize/vermouth/molecule.py", line 447, in subgraph
    node_copies = [(node, copy.copy(self.nodes[node])) for node in nodes]
  File "/mnt/c/Users/dr19502/PDB/src/vermouth-martinize/vermouth/molecule.py", line 447, in <listcomp>
    node_copies = [(node, copy.copy(self.nodes[node])) for node in nodes]
  File "/home/jon/miniconda3/envs/vermouth/lib/python3.8/site-packages/networkx/classes/reportviews.py", line 187, in __getitem__
    return self._nodes[n]
KeyError: 7510
```

This occurs in the following PDBs:
* 4zza
* 4zz4
* 2zye
* 2zwb
* 4zv0
* 2zp9
* 2zp8
* 2zpp
* 5zo0
* 2zio
* 5zn0
* 3zgi
* 5a90
* 4a7e
* 5a5b
* 487d

**Comment by pckroon** [comment] 2021-03-15 13:11
I can't reproduce the issue reliably for all cases here, but I think I fixed it using 2zwb as testcase. There were 2 main issues:
1) Element D is unknown to make_bonds, which results in very strange "modifications" that have no anchor, since they get no bonds. Fixed by teaching make_bonds about 'D'. A better solution might be to check for the absence of anchors when canonicalizing modifications?
2) The real issue: if a residue contains 2 (or more) modifications, and the first is not known. Once the first modification gets IDed as 'unknown' the relevant atoms get removed from the molecule. When the second modification comes around the processor tries to create a subgraph of the complete residue (based on bookkeeping done earlier), resulting in the KeyError. Fixed by keeping track of which atoms got removed.

PR forthcoming.

**Closed** 2021-03-29 13:53 UTC
