### ISSUE TITLE
The file for the formal Martini 3

### ISSUE THREAD

**Issue by xiki-tempula** [marrink-lab/vermouth-martinize#361] opened 2021-04-22 11:06 UTC
I'm interested in using martinize2 to generate the force field for the new Martini 3 force field.

The command recommended by the nature method paper SI, at page 96 is:

```
martinate.sh -f 2oar.pdb -fetch opm --insane-d=5 --insane-l=DPPC --
insane-sol=W -martinize /path/to/martinize2 -ffdir /path/to/martini3 -
cg martini304
```

I think the command should be
`martinize2 -f protein.pdb -x CG.pdb -dssp mkdssp -elastic -nt -ff martini304 -maxwarn 11 -o CG.top`

However, it complains about martini304 not being a valid force field. After some check at the repo, I think it should be
`martinize2 -f protein.pdb -x CG.pdb -dssp mkdssp -elastic -nt -ff martini3001 -maxwarn 11 -o CG.top`

However, given that there are multiple version of martini3 in https://github.com/marrink-lab/vermouth-martinize/tree/master/vermouth/data/force_fields, it is not very clear if this is the formal version or the first dev version.

**Comment by pckroon** [comment] 2021-04-22 11:09
Hi,

To first answer the question, you need martini3001; this is also the default argument.
The other versions are beta versions. I'll see about marking those more clearly. Thanks for bringing this to our attention!

**Comment by xiki-tempula** [comment] 2021-04-22 11:13
@pckroon Thank you for the fast response. 

If one has not read the paper, it is quite clear that martini3001 is the correct version. However, given that the paper referenced martini304, it becomes a bit unclear.

In the beta version, there is a vmd script for adding dihedral correction based on the crystal structure. I think the paper has also recommended this approach. I wonder if there is any way for martinize2 to do this? 
I have checked that the dihedral correction would not be added by default and there doesn't seems to be an option in martinize2 for this?

**Comment by pckroon** [comment] 2021-04-22 11:35
I can't find the dihedral corrections you mention in the paper+SI. Do you mean the restricted bending potentials by Bulacu et al? (SI-C4/Numerical instabilities caused by dihedral potentials)? If you mean the "sidechain fix" (Herzog et al, 10.1021/acs.jctc.6b00122): you *should* be able to add those with the `-scfix` flag. Look for the string `scfix` in `martini3001/aminoacids.ff`

**Comment by xiki-tempula** [comment] 2021-04-22 11:42
@pckroon Thank you. Yes, I think this is what I'm looking for.
I cannot find it in the paper but in the beta version, it is said that 

```
Besides, we recommend the addition of side chain dihedral corrections to the model based in the crystallographic structure. You can do it using VMD (15), an adapted addDihedral.tcl (16)and bbsc.sh scripts.
./bbsc.sh Protein.itp protein.pdb
```

**Comment by pckroon** [comment] 2021-04-22 12:29
I finally found the scripts you mentioned, and it is indeed the scfix by Herzog. The `-scfix` should do the trick.
I'll leave this issue open since we need to rename the beta martini versions

**Comment by oliverdutton** [comment] 2021-04-23 07:52
Where are the itp files to go with martini3001?

**Comment by pckroon** [comment] 2021-04-23 07:59
The itp with particle definitions can be found on cgmartini.nl, here specifically: http://cgmartini.nl/index.php/force-field-parameters/particle-definitions

ITPs for specific molecules will also be on cgmartini.nl

Protein parameters will be in vermouth/data/force_fields/martini3001: https://github.com/marrink-lab/vermouth-martinize/tree/master/vermouth/data/force_fields/martini3001

**Comment by oliverdutton** [comment] 2021-04-23 08:47
Thank you very much, I couldn't find the 3001 itp's, I kept ending up at the 3.0.b.3.2 versions. Thank you.

Big problems are easy, small problems are a nightmare.

**Comment by OLaprevote** [comment] 2021-04-26 12:24
There is something I fail to understand here @pckroon. To me `martinate.sh` is referring to the script that can be found in gromit repository from Marrink lab ([https://github.com/marrink-lab/gromit](https://github.com/marrink-lab/gromit)), as stated in the nature method paper SI (p. 95).

While martinize2 goal is to make the conversion of proteins into coarse-grain easy, `martinate.sh` permits to do the solvation, embed in membrane, and even run energy minimization and equilibrations. So no, the command that @xiki-tempula is proposing is NOT a replacement.

Did I not understand right?

**Comment by pckroon** [comment] 2021-04-26 13:08
martinate and martinize do not do the same thing indeed. Martinize does not embed/solvate/etc.
So to be complete, I think 
```bash
martinate.sh -f 2oar.pdb -fetch opm --insane-d=5 --insane-l=DPPC --
insane-sol=W -martinize /path/to/martinize2 -f protein.pdb -x CG.pdb -dssp mkdssp -elastic -nt -ff martini304 -maxwarn 11 -o CG.top
```
should be a complete replacement. I also thought that was what @xiki-tempula meant.

**Comment by OLaprevote** [comment] 2021-04-26 13:23
This command doesn't work on my computer. at least not if calling martinize2 from your $PATH. This does:
```
martinate.sh -f 2oar.pdb -fetch opm --insane-d=5 --insane-l=DPPC --insane-sol=W -martinize martinize2 --martinize-x=CG.pdb --martinize-dssp=mkdssp --martinize-elastic --martinize-nt --martinize-ff=martini3001 --martinize-maxwarn=11 --martinize-o=CG.top
```
(There would be a bug, as described [here](http://cgmartini.nl/index.php/component/kunena/9-tools/5998-gromit-martinate-sh-using-martini3), but that's another matter.)

**Closed** 2022-05-10 13:12 UTC
Labels: FAQ
