### ISSUE TITLE
Applying patches to residues

### ISSUE THREAD

**Issue by biomolsim** [marrink-lab/vermouth-martinize#417] opened 2022-04-21 13:30 UTC
Hey everyone,

I want to apply a neutral aspartate (ASP0) patch to one of the aspartate residues in a protein. However, I could not figure out how to implement that. I tried `-modify A-ASP164:ASP0`, but that didn't work out. Hence, I decided to do the pre-processing with VMD and tried coarse-graining with `martinize2` after that.

Although `martinize2` successfully detected the patched aspartate residue but was unable to perform the coarse-graining. Interestingly, the additional errors with HSD residue were not observed when an HSE model of histidine was provided instead to `martinize2` #389.

Please suggest some alternative solutions that could fix this problem. Thanks a lot.

```
martinize2 -f prot.pdb -dssp /usr/bin/dssp -ff elnedyn22p -x cg_prot.pdb

    INFO - general - Read 1 molecules from PDB file prot.pdb
    INFO - step - Guessing the bonds.
    INFO - general - 1 molecules after guessing bonds
    INFO - step - Repairing the graph.
    INFO - general - Applying modification N-ter to residue A-LEU61
    INFO - general - Applying modification C-ter to residue A-ASN346
    INFO - step - Dealing with modifications.
    INFO - general - Identified the modifications ['N-ter'] on residues ['LEU61', 'LEU61', 'LEU61', 'LEU61']
    INFO - general - Identified the modifications ['ASP0'] on residues ['ASP164']
    INFO - general - Identified the modifications ['HSD'] on residues ['HIS151']
    INFO - general - Identified the modifications ['HSD'] on residues ['HIS219']
    INFO - general - Identified the modifications ['HSD'] on residues ['HIS307']
    INFO - general - Identified the modifications ['HSD'] on residues ['HIS328']
    INFO - general - Identified the modifications ['C-ter'] on residues ['ASN346', 'ASN346', 'ASN346']
    INFO - step - Read input.
    INFO - step - Creating the graph at the target resolution.
 WARNING - general - Can't find modification mappings for the modifications ['HSD']. The following modification mappings are known: {('C-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e968e0>, ('N-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e96850>, ('COOH-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e96880>, ('NH2-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e969d0>}
 WARNING - general - Can't find modification mappings for the modifications ['HSD']. The following modification mappings are known: {('C-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e968e0>, ('N-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e96850>, ('COOH-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e96880>, ('NH2-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e969d0>}
 WARNING - general - Can't find modification mappings for the modifications ['HSD']. The following modification mappings are known: {('C-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e968e0>, ('N-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e96850>, ('COOH-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e96880>, ('NH2-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e969d0>}
 WARNING - general - Can't find modification mappings for the modifications ['HSD']. The following modification mappings are known: {('C-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e968e0>, ('N-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e96850>, ('COOH-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e96880>, ('NH2-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e969d0>}
 WARNING - general - Can't find modification mappings for the modifications ['ASP0']. The following modification mappings are known: {('C-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e968e0>, ('N-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e96850>, ('COOH-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e96880>, ('NH2-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e969d0>}
    INFO - general - Applying modification mapping ('N-ter',)
    INFO - general - Applying modification mapping ('C-ter',)
    INFO - step - Averaging the coordinates.
    INFO - step - Applying the links.
    INFO - step - Placing the charge dummies.
    INFO - step - Applying position restraints.
    INFO - step - Setting the rubber bands.
    INFO - step - Writing output.
    INFO - general - Please cite: Marrink, S J; Risselada, H J; Yefimov, S; Tieleman, D P; De Vries, A H;  The journal of physical chemistry B 2007
    INFO - general - Please cite: Periole, X; Cavalli, M; Marrink, S J; Ceruso, M A;  Journal of chemical theory and computation 2009
    INFO - general - Please cite: Yesylevskyy, S O; Schaefer, L V; Sengupta, D; Marrink, S J;  PLoS Comput Biol 2010
    INFO - general - Please cite: Monticelli, L; Kandasamy, S K; Periole, X; Larson, R G; Tieleman, D P; Marrink, S J;  Journal of chemical theory and computation 2008
    INFO - general - Please cite: de Jong, D H; Singh, G; Bennett, W D; Arnarez, C; Wassenaar, T A; Schaefer, L V; Periole, X; Tieleman, D P; Marrink, S J;  Journal of chemical theory and computation 2013
   ERROR - general - 5 warnings were encountered after accounting for the -maxwarn flag. No output files will be written. Consider fixing the warnings, or if you are su
```

**Comment by pckroon** [comment] 2022-04-25 09:36
The issue is that the information needed to map the modification to martini is missing:
```
 WARNING - general - Can't find modification mappings for the modifications ['HSD']. The following modification mappings are known: {('C-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e968e0>, ('N-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e96850>, ('COOH-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e96880>, ('NH2-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e969d0>}
 WARNING - general - Can't find modification mappings for the modifications ['HSD']. The following modification mappings are known: {('C-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e968e0>, ('N-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e96850>, ('COOH-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e96880>, ('NH2-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e969d0>}
 WARNING - general - Can't find modification mappings for the modifications ['HSD']. The following modification mappings are known: {('C-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e968e0>, ('N-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e96850>, ('COOH-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e96880>, ('NH2-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e969d0>}
 WARNING - general - Can't find modification mappings for the modifications ['HSD']. The following modification mappings are known: {('C-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e968e0>, ('N-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e96850>, ('COOH-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e96880>, ('NH2-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e969d0>}
 WARNING - general - Can't find modification mappings for the modifications ['ASP0']. The following modification mappings are known: {('C-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e968e0>, ('N-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e96850>, ('COOH-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e96880>, ('NH2-ter',): <vermouth.map_parser.Mapping object at 0x7f2281e969d0>}
```

I honesty I don't know if parameters for amino acids with non-standard protonation states are even available for martini3 yet. @fgrunewald do you know?

**Comment by fgrunewald** [comment] 2022-04-25 09:40
We're working on those. They are currently not released as far as I know. I started pooling all these issue into a project, that will get resolved as soon as those parameters become available.

**Comment by biomolsim** [comment] 2022-04-25 11:20
Hello @pckroon, thank you for your reply. Although I am trying to implement this with `elnedyn22p`, not `martini3001`.

**Comment by pckroon** [comment] 2022-04-26 09:55
Oh oops. My bad.

To be honest I also don't know if there's elnedyn (or martini2) parameters for amino acids with non-standard protonations (for some I guess). I also don't know what martinize1 did with them. Since I'm not in the field anymore I also don't really have time to find out. If you can find the parameters for me I can help you make the requisite mappings and modifications though :)

**Comment by biomolsim** [comment] 2022-04-27 20:25
As in the case of HSP (protonated histidine), I added ASPP blocks to the relevant directories in the `data ` folder. It seems to have worked, and the neutral aspartate does not have the SCN bead.

**Comment by biomolsim** [comment] 2022-04-27 20:27
As for HSD residue, I assume it would be similar to HSE after coarse-graining, and hence I am using the same mapping scheme.

**Comment by fgrunewald** [comment] 2022-07-22 16:17
This has been solved. Now residue names for pronated residues following Amber or Charmm naming scheme are available.

**Closed by fgrunewald** 2022-07-22 16:17 UTC
Labels: duplicate, data
