### ISSUE TITLE
Dssp error for two peptide system

### ISSUE THREAD

**Issue by azadeha83** [marrink-lab/vermouth-martinize#382] opened 2021-09-15 09:48 UTC
Dear all,

I have a two peptide (similar) system in atomistic representation and intend to map it to coarse-grain using martini3. This is the command I use:

martinize2 -f protein.pdb -from universal -ff martini3001 -x protein_CG.pdb -o protein_CG.top -nt -p backbone -dssp mkdssp

However, running the command raises an error related to dssp.

I would appreciate any kind of help.

    INFO - general - Read 1 molecules from PDB file tmd_double_centered_changedsegname.pdb
    INFO - step - Guessing the bonds.
    INFO - general - 2 molecules after guessing bonds
    INFO - step - Repairing the graph.
    INFO - general - Applying modification NH2-ter to residue A-ALA1
    INFO - general - Applying modification COOH-ter to residue A-ASN32
    INFO - general - Applying modification NH2-ter to residue B-ALA1
    INFO - general - Applying modification COOH-ter to residue B-ASN32
    INFO - step - Dealing with modifications.
    INFO - general - Identified the modifications ['NH2-ter'] on residues ['ALA1', 'ALA1', 'ALA1', 'ALA1']
    INFO - general - Identified the modifications ['COOH-ter'] on residues ['ASN32', 'ASN32', 'ASN32']
    INFO - general - Identified the modifications ['NH2-ter'] on residues ['ALA1', 'ALA1', 'ALA1', 'ALA1']
    INFO - general - Identified the modifications ['COOH-ter'] on residues ['ASN32', 'ASN32', 'ASN32']
    INFO - step - Read input.
Traceback (most recent call last):
  File "/home/a/aalaviza/.local/bin/martinize2", line 797, in <module>
    entry()
  File "/home/a/aalaviza/.local/bin/martinize2", line 640, in entry
    AnnotateDSSP(executable=args.dssp, savedir='.').run_system(system)
  File "/home/a/aalaviza/.local/lib/python3.6/site-packages/vermouth/processors/processor.py", line 37, in run_system
    mols.append(self.run_molecule(molecule))
  File "/home/a/aalaviza/.local/lib/python3.6/site-packages/vermouth/dssp/dssp.py", line 458, in run_molecule
    annotate_dssp(molecule, self.executable, self.savedir)
  File "/home/a/aalaviza/.local/lib/python3.6/site-packages/vermouth/dssp/dssp.py", line 289, in annotate_dssp
    secstructs = run_dssp(system, executable, savefile)
  File "/home/a/aalaviza/.local/lib/python3.6/site-packages/vermouth/dssp/dssp.py", line 214, in run_dssp
    raise DSSPError(message.format(err=process.stderr, file=tmpfile_name))
vermouth.dssp.dssp.DSSPError: DSSP encountered an error. The message was Error parsing PDB at line 1
Error trying to load file "/scratch/tmp/aalaviza/martini3/my_system/dssp_in_nnsxmoeu.pdb"
Expected record CRYST1 but found ATOM  
. The input file provided to DSSP can be found at /scratch/tmp/aalaviza/martini3/my_system/dssp_in_nnsxmoeu.pdb.

Best regards,
Azadeh

**Comment by pckroon** [comment] 2021-09-16 11:56
Closed as duplicate of #364

**Closed by pckroon** 2021-09-16 11:56 UTC
